# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/glasskube
  - id: package-operator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: ./cmd/package-operator
    binary: package-operator

dockers:
  - use: docker
    dockerfile: release.Dockerfile
    image_templates:
      - "ghcr.io/glasskube/package-operator:{{ .Tag }}"

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Arch }}'
    homepage: https://glasskube.dev
    maintainer: 'Philip Miglinci <pmig@glasskube.eu>'
    description: >-
      Glasskube is a cloud native package manager for Kubernetes. It includes an UI and CLI, is dependency aware and GitOps ready.
    license: "Apache-2.0"
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/nfpm/copyright
        file_info:
          mode: 0644

brews:
  - name: glasskube
    homepage: https://glasskube.dev
    description: >-
      Glasskube is a cloud native package manager for Kubernetes. It includes an UI and CLI, is dependency aware and GitOps ready.
    license: "Apache-2.0"
    repository:
      owner: glasskube
      name: homebrew-glasskube
    url_template: "https://releases.dl.glasskube.dev/{{ .ArtifactName }}"
    commit_author:
      name: glasskube-bot
      email: githubbot@glasskube.eu
    commit_msg_template: "chore: brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    install: |
      bin.install "glasskube"


archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Tag }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    allow_different_binary_count: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
