# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - make web
    - go mod tidy
    - go generate ./...
    - hack/generate-manifests.sh

builds:
  - id: glasskube
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/glasskube
    ldflags:
      - "-s -w -X github.com/glasskube/glasskube/internal/config.Version={{.Version}} -X github.com/glasskube/glasskube/internal/config.Commit={{.ShortCommit}} -X github.com/glasskube/glasskube/internal/config.Date={{.Date}}"
  - id: package-operator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: ./cmd/package-operator
    ldflags:
      - "-s -w -X github.com/glasskube/glasskube/internal/config.Version={{.Version}} -X github.com/glasskube/glasskube/internal/config.Commit={{.ShortCommit}} -X github.com/glasskube/glasskube/internal/config.Date={{.Date}}"
    binary: package-operator
  - id: cert-manager
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: ./cmd/cert-manager
    binary: cert-manager

dockers:
  - image_templates:
      - "ghcr.io/glasskube/package-operator:{{.Tag}}-amd64"
      - "ghcr.io/glasskube/package-operator:latest-amd64"
    use: buildx
    dockerfile: package-operator.Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - '--label=org.opencontainers.image.title="Glasskube package-operator"'
      - "--label=org.opencontainers.image.vendor=Glasskube"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
      - "--label=org.opencontainers.image.source=https://github.com/glasskube/glasskube/"
      - "--label=org.opencontainers.image.url=https://glasskube.dev/"
      - "--label=org.opencontainers.image.documentation=https://glasskube.dev/docs/"
  - image_templates:
      - "ghcr.io/glasskube/package-operator:{{.Tag}}-arm64"
      - "ghcr.io/glasskube/package-operator:latest-arm64"
    use: buildx
    dockerfile: package-operator.Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - '--label=org.opencontainers.image.title="Glasskube package-operator"'
      - "--label=org.opencontainers.image.vendor=Glasskube"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
      - "--label=org.opencontainers.image.source=https://github.com/glasskube/glasskube/"
      - "--label=org.opencontainers.image.url=https://glasskube.dev/"
      - "--label=org.opencontainers.image.documentation=https://glasskube.dev/docs/"
    goarch: arm64
  - image_templates:
      - "ghcr.io/glasskube/glasskube:{{.Tag}}-amd64"
      - "ghcr.io/glasskube/glasskube:latest-amd64"
    use: buildx
    dockerfile: glasskube.Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - '--label=org.opencontainers.image.title="Glasskube CLI"'
      - "--label=org.opencontainers.image.vendor=Glasskube"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
      - "--label=org.opencontainers.image.source=https://github.com/glasskube/glasskube/"
      - "--label=org.opencontainers.image.url=https://glasskube.dev/"
      - "--label=org.opencontainers.image.documentation=https://glasskube.dev/docs/"
  - image_templates:
      - "ghcr.io/glasskube/glasskube:{{.Tag}}-arm64"
      - "ghcr.io/glasskube/glasskube:latest-arm64"
    use: buildx
    dockerfile: glasskube.Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - '--label=org.opencontainers.image.title="Glasskube CLI"'
      - "--label=org.opencontainers.image.vendor=Glasskube"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
      - "--label=org.opencontainers.image.source=https://github.com/glasskube/glasskube/"
      - "--label=org.opencontainers.image.url=https://glasskube.dev/"
      - "--label=org.opencontainers.image.documentation=https://glasskube.dev/docs/"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/glasskube/package-operator:{{.Tag}}"
    image_templates:
      - "ghcr.io/glasskube/package-operator:{{.Tag}}-amd64"
      - "ghcr.io/glasskube/package-operator:{{.Tag}}-arm64"
  - name_template: "ghcr.io/glasskube/package-operator:latest"
    image_templates:
      - "ghcr.io/glasskube/package-operator:latest-amd64"
      - "ghcr.io/glasskube/package-operator:latest-arm64"
  - name_template: "ghcr.io/glasskube/glasskube:{{.Tag}}"
    image_templates:
      - "ghcr.io/glasskube/glasskube:{{.Tag}}-amd64"
      - "ghcr.io/glasskube/glasskube:{{.Tag}}-arm64"
  - name_template: "ghcr.io/glasskube/glasskube:latest"
    image_templates:
      - "ghcr.io/glasskube/glasskube:latest-amd64"
      - "ghcr.io/glasskube/glasskube:latest-arm64"

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Arch }}"
    homepage: https://glasskube.dev
    maintainer: "Philip Miglinci <pmig@glasskube.eu>"
    description: >-
      Glasskube is a cloud native package manager for Kubernetes. It includes an UI and CLI, is dependency aware and GitOps ready.
    license: "Apache-2.0"
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/glasskube/copyright
        file_info:
          mode: 0644
    builds:
      - glasskube

brews:
  - name: glasskube
    homepage: https://glasskube.dev
    description: >-
      Glasskube is a cloud native package manager for Kubernetes. It includes an UI and CLI, is dependency aware and GitOps ready.
    license: "Apache-2.0"
    repository:
      owner: glasskube
      name: homebrew-tap
    url_template: "https://releases.dl.glasskube.dev/{{ .ArtifactName }}"
    commit_author:
      name: glasskube-bot
      email: githubbot@glasskube.eu
    commit_msg_template: "chore: brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    install: |
      bin.install "glasskube"
    post_install: |
      generate_completions_from_executable(bin/"glasskube", "completion")
    skip_upload: "auto"

release:
  prerelease: auto
  mode: keep-existing
  extra_files:
    - glob: ./build/manifest/*

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Tag }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - glasskube

changelog:
  disable: true
