apiVersion: batch/v1
kind: Job
metadata:
  name: webhook-cert-init
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          image: controller:latest
          command:
            - /cert-manager
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: webhook-cert
      restartPolicy: OnFailure
