# permissions for end users to view clusterpackages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: glasskube
    app.kubernetes.io/managed-by: kustomize
  name: clusterpackage-viewer-role
rules:
- apiGroups:
  - packages.glasskube.dev
  resources:
  - clusterpackages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - packages.glasskube.dev
  resources:
  - clusterpackages/status
  verbs:
  - get
