# permissions for end users to edit packagerepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: glasskube
    app.kubernetes.io/managed-by: kustomize
  name: packagerepository-editor-role
rules:
- apiGroups:
  - packages.glasskube.dev
  resources:
  - packagerepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - packages.glasskube.dev
  resources:
  - packagerepositories/status
  verbs:
  - get
