# permissions for end users to edit packageinfos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: packageinfo-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: glasskube
    app.kubernetes.io/part-of: glasskube
    app.kubernetes.io/managed-by: kustomize
  name: packageinfo-editor-role
rules:
- apiGroups:
  - packages.glasskube.dev
  resources:
  - packageinfos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - packages.glasskube.dev
  resources:
  - packageinfos/status
  verbs:
  - get
