# permissions for end users to view packages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: package-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: glasskube
    app.kubernetes.io/part-of: glasskube
    app.kubernetes.io/managed-by: kustomize
  name: package-viewer-role
rules:
- apiGroups:
  - packages.glasskube.dev
  resources:
  - packages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - packages.glasskube.dev
  resources:
  - packages/status
  verbs:
  - get
