---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - packages.glasskube.dev
  resources:
  - clusterpackages
  - packageinfos
  - packagerepositories
  - packages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - packages.glasskube.dev
  resources:
  - clusterpackages/finalizers
  - packageinfos/finalizers
  - packagerepositories/finalizers
  - packages/finalizers
  verbs:
  - update
- apiGroups:
  - packages.glasskube.dev
  resources:
  - clusterpackages/status
  - packageinfos/status
  - packagerepositories/status
  - packages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - helmrepositories
  verbs:
  - create
  - get
  - list
  - update
  - watch
