# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - bases/packages.glasskube.dev_packages.yaml
  - bases/packages.glasskube.dev_packageinfos.yaml
  - bases/packages.glasskube.dev_packagerepositories.yaml
  - bases/packages.glasskube.dev_clusterpackages.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
  # [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
  # patches here are for enabling the conversion webhook for each CRD
  - path: patches/webhook_in_packages.yaml
  - path: patches/webhook_in_clusterpackages.yaml
#- path: patches/webhook_in_packageinfos.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_packages.yaml
#- path: patches/cainjection_in_packageinfos.yaml
#- path: patches/cainjection_in_packagerepositories.yaml
#- path: patches/cainjection_in_clusterpackages.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

configurations:
  - kustomizeconfig.yaml
