apiVersion: batch/v1
kind: CronJob
metadata:
  name: glasskube-autoupdate
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
          containers:
            - name: glasskube
              image: ghcr.io/glasskube/glasskube
              args:
                - auto-update
                - --skip-update-check
          serviceAccountName: glasskube-autoupdate
          restartPolicy: OnFailure
