apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: glasskube-autoupdate
rules:
  - verbs:
      - update
      - patch
    apiGroups:
      - packages.glasskube.dev
    resources:
      - packages
      - clusterpackages
  - verbs:
      - get
      - list
    apiGroups:
      - packages.glasskube.dev
    resources:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: glasskube-autoupdate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: glasskube-autoupdate
subjects:
  - kind: ServiceAccount
    name: glasskube-autoupdate
