import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  guides: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ]
};

export default sidebars;
