apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - clientConfig:
      service:
        port: 9443
    name: vpackage.kb.io
  - clientConfig:
      service:
        port: 9443
    name: vclusterpackage.kb.io
